GET http://localhost:3001/places?text=Avenida amapá, 54, cianorte pr

###
@originId=ChIJZYCE48hT7ZQRkPQk2tppNcA
@destinationId=ChIJI_2qzatQ7ZQRVxRntvK32U8
###
GET http://localhost:3001/directions?originId={{originId}}&destinationId={{destinationId}}

###
POST http://localhost:3001/routes
Content-Type: application/json

{
    "name": "Rota 1",
    "source_id": "{{ originId }}",
    "destination_id": "{{ destinationId }}"
}

###
POST http://localhost:3001/routes/675cd77f26874abb321b40df/start


###
GET http://localhost:3001/routes

###
GET http://localhost:3001/routes/675727898d5be95228a4d7ff
